<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
<xacro:property name="dist" value="1.0" /> <!-- Link 3 -->
<xacro:property name="mass_obj" value="1" /> <!-- arbitrary value for mass -->
<xacro:property name="width" value="0.2" /> <!-- Square dimensions (widthxwidth) of beams -->
<xacro:property name="height" value=".4" /> <!-- Link 1 -->
  <!-- Constants for robot dimensions -->
  

<link name="box">
    <collision>
      <origin xyz="-1 ${dist} ${height/2}" rpy="0 0 0"/>
      <geometry>	
	<box size="${width} ${width} ${height}"/>
      </geometry>
    </collision>
   <visual>
      <origin xyz="-1 ${dist} ${height/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="-1 ${2.0} 0.5" rpy="0 0 0"/>
      <mass value="${mass_obj}"/>
      <inertia
	  ixx="${mass_obj / 12.0 * (width*width + height*height)}" ixy="0.0" ixz="0.0"
	  iyy="${mass_obj / 12.0 * (height*height + width*width)}" iyz="0.0"
	  izz="${mass_obj / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  
  <!--xarco:macro name="grip_plam" params="prefix"-->
<link name="box1">
    <!--collision>
      <origin xyz="-1 ${dist} .05" rpy="0 0 0"/>
      <geometry>	
	<box size=".4 .2 .1"/>
      </geometry>
    </collision>
   <visual>
      <origin xyz="-1 ${dist} .05" rpy="0 0 0"/>
      <geometry>
	<box size=".4 .2 .1"/>
      </geometry>
      <material name="orange"/>
    </visual-->

    <inertial>
      <origin xyz="-1 ${2.0} 0.1" rpy="0 0 0"/>
      <mass value="${mass_obj}"/>
      <inertia
	  ixx="${mass_obj / 12.0 * (width*width + height*height)}" ixy="0.0" ixz="0.0"
	  iyy="${mass_obj / 12.0 * (height*height + width*width)}" iyz="0.0"
	  izz="${mass_obj / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>
  <!--joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="box1"/>
  </joint-->
  <!--joint name="linx_joint" type="prismatic">
    <parent link="world"/>
    <child link="box"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="5" effort="1000" velocity="1.0"/>
  </joint>
  
  </xarco:macro>
  <joint name="joint_plam" type="prismatic">
    <parent link="world"/>
    <child link="box"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="5" effort="1000" velocity="1.0"/>
  </joint-->
  
  <!--joint name="liny_joint" type="prismatic">
    <parent link="link1"/>
    <child link="box"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="5" effort="1000" velocity="0.2"/>
  </joint-->

  



<transmission name="lx_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="linx_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface </hardwareInterface>
    </joint>  
    <actuator name="lx_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface </hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>
<!--transmission name="left_fin_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_lf">
      <hardwareInterface>hardware_interface/VelocityJointInterface </hardwareInterface>
    </joint>  
    <actuator name="lf_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface </hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission-->
<transmission name="ly_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="liny_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface </hardwareInterface>
    </joint>  
    <actuator name="ly_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface </hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>
</robot>

 
